name: td_erpnext
executable: td-erpnext
description: Tool for automize backups and the management of the erpnext service under ubuntu.
version: 1.0.0
publish_to: none
entrypoint: main.dart

environment:
  sdk: ^3.10.6

dependencies:
  path: ^1.9.0
  natrix:
    path: ../natrix
  stepflow:
    path: ../stepflow
  yaml: ^3.1.0