# Enable automatic backups
do_backups: true


# These parameters vary because of the docker image configuration.
# Set them to ensure the functionality of the interface between this
# application and the managed ERPNext Docker Container.
parameter:
  port: 8080
  erpnext_site_name: "frontend"
  docker_frappe_backend_container_name: "frappe_docker_frontend_1"