import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:stepflow/io.dart';
import 'package:stepflow/core.dart';
import 'package:td_erpnext/src/log_color.dart';
import 'package:td_erpnext/src/settings.dart';
import 'src/docker.dart';

class ERPNextBackup extends ConfigureStep {
  final DockerContainer container;
  final String currentSiteName;
  final DockerOutputCallback? onCallback;
  final String backupSourcePath;
  final String backupDestinationPath;

  ERPNextBackup({
    required this.container,
    required this.currentSiteName,
    required this.onCallback,
    required this.backupSourcePath,
    required this.backupDestinationPath,
  });
  @override
  Step configure() {
    final String backupDestinationPackagePath = path.join(
      backupDestinationPath,
      DateTime.now()
          .toLocal()
          .toIso8601String()
          .substring(0, 18)
          .replaceAll(":", "_"),
    );
    Directory(backupDestinationPackagePath).createSync(recursive: true);
    return Chain(
      steps: [
        Chain(
          steps: [
            Docker.execute(
              container: container,
              program: "bench",
              arguments: [
                "--site",
                currentSiteName,
                "backup",
                "--with-files",
                "--compress",
              ],
              onCallback: onCallback,
            ),
            // The bench backup command creates files in sites/<site>/private/backups
            // The exact filenames are generated by bench.
            // We expect the backupSourcePath to point to that directory.
            Docker.copy(
              source: DockerLocation.container(container, backupSourcePath),
              destination: DockerLocation.host(backupDestinationPackagePath),
              onCallback: onCallback,
            ),
            // Optionally cleanup the container backup folder to save space
            Docker.execute(
              container: container,
              settings: DockerExecSettings(
                workingDirectory: path.dirname(backupSourcePath),
                user: "root",
              ),
              program: "rm",
              arguments: ["-r", "-f", path.basename(backupSourcePath)],
            ),
            Docker.run(
              image: DockerImage.busybox,
              program: "tar",
              arguments: [
                "-cvzf",
                "backup/erpnext_volumes_backup.tar.gz",
                // We want to backup the data volumes.
                // Usually these are mounted under /home/frappe/frappe-bench
                "home/frappe/frappe-bench",
              ],
              settings: DockerRunSettings(
                remove: true,
                volumesFrom: [container],
                volumes: [
                  DockerVolume(
                    hostPath: backupDestinationPackagePath,
                    containerPath: "/backup",
                  ),
                ],
              ),
              onCallback: onCallback,
            ),
            Runnable((context) => onCallback?.call(context, "Backup ${LogColor.cyan(path.basename(backupDestinationPackagePath))} stored under ${path.dirname(backupDestinationPackagePath)}.".codeUnits, false))
          ],
        ),
      ],
    );
  }
}

class ERPNextRestore extends ConfigureStep {
  final DockerContainer container;
  final String currentSiteName;
  final String backupDestinationPath;
  final String backupSourcePath;
  final String workingDirectory;
  final DockerOutputCallback? onCallback;

  ERPNextRestore({
    required this.container,
    required this.currentSiteName,
    required this.onCallback,
    required this.backupSourcePath,
    required this.backupDestinationPath,
    required this.workingDirectory,
  });

  @override
  Step configure() {
    final String composeFilePath = path.join(
      settingsAtProgramStart.appDirectoryPath,
      "frappe_docker",
      "pwd.yml",
    );
    late final String backupPath;
    final directory = Directory(backupDestinationPath);
    bool found = false;
    if (directory.existsSync()) {
      final List<FileSystemEntity> entities = directory
          .listSync()
          .whereType<Directory>()
          .toList();
      entities.sort(
        (a, b) => b.path.compareTo(a.path),
      ); // Sort by name descending (ISO date)
      if (entities.isNotEmpty) {
        backupPath = entities.first.path;
        found = true;
      }
    }
    
    if (!found) {
      return Runnable((context) => context.pop("No backups found at $backupDestinationPath."));
    }

    final dir = Directory(path.join(backupPath, "backups"));
    final List<File> sqlFiles = dir
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith(".sql.gz"))
        .toList();
    final String? sqlFile = sqlFiles.isNotEmpty
        ? sqlFiles.first.path
        : null;

    return Chain(
      steps: [
        // 1. Stop containers before restoring volumes
        DockerCompose.stop(
          composeFile: File(composeFilePath),
          workingDirectory: workingDirectory,
          onCallback: onCallback,
        ),
        // 2. Restore Volumes
        Docker.run(
          image: DockerImage.busybox,
          program: "tar",
          arguments: [
            "-xvzf",
            "backup/erpnext_volumes_backup.tar.gz",
            "-C",
            "/",
          ],
          settings: DockerRunSettings(
            remove: true,
            volumesFrom: [container],
            volumes: [
              DockerVolume(hostPath: backupPath, containerPath: "/backup"),
            ],
          ),
          onCallback: onCallback,
        ),
        // 3. Start containers again
        DockerCompose.init(
          composeFile: File(composeFilePath),
          workingDirectory: workingDirectory,
          detach: true,
          onCallback: onCallback,
        ),
        // 4. Restore bench backup (to fix potential DB corruption)
        Conditional(
          condition: sqlFile != null,
          child: Chain(
            steps: [
              // Create directory in container if not exists
              Docker.execute(
                container: container,
                program: "mkdir",
                arguments: ["-p", backupSourcePath],
                settings: const DockerExecSettings(user: "frappe"),
              ),
              // Copy the SQL file back to container
              Docker.copy(
                source: DockerLocation.host(sqlFile ?? ""),
                destination: DockerLocation.container(
                  container,
                  backupSourcePath,
                ),
                onCallback: onCallback,
              ),
              // Run bench restore
              Docker.execute(
                container: container,
                program: "bench",
                arguments: [
                  "--site",
                  currentSiteName,
                  "restore",
                  path.join(backupSourcePath, path.basename(sqlFile ?? "")),
                  "--yes",
                ],
                onCallback: onCallback,
              ),
            ],
          ),
        ),
        Conditional(
          condition: sqlFile == null,
          child: Runnable(
            (context) => context.send(
              Response(
                "No SQL backup found in $backupPath, skipping bench restore.",
                Level.warning,
              ),
            ),
          ),
        ),
      ],
    );
  }
}

class ERPNextInstall extends ConfigureStep {
  final DockerOutputCallback? onCallback;
  final String appDirectoryPath;
  const ERPNextInstall._internal({
    this.onCallback,
    required this.appDirectoryPath,
  });

  factory ERPNextInstall({
    DockerOutputCallback? onCallback,
    required String appDirectoryPath,
  }) {
    return ERPNextInstall._internal(
      onCallback: onCallback,
      appDirectoryPath: appDirectoryPath,
    );
  }

  @override
  Step configure() {
    final String composeFilePath = path.join(
      appDirectoryPath,
      "frappe_docker",
      "pwd.yml",
    );
    return Chain(
      steps: [
        Check(
          programs: ["docker", "git", "systemctl", "systemd"],
          onFailure: (context, programs) => context.pop(
            "The following dependencies aren't satisfied: ${programs.join(", ")}. ",
          ),
        ),
        Conditional(
          condition: !Directory(
            path.join(appDirectoryPath, "frappe_docker"),
          ).existsSync(),
          child: Chain(
            steps: [
              CreateDirectory(
                appDirectoryPath,
                recursive: true,
                deleteIfExists: true,
              ),
              Shell(
                program: "git",
                arguments: ["clone", "https://github.com/frappe/frappe_docker"],
                options: ProcessInterfaceOptions(
                  workingDirectory: appDirectoryPath,
                ),
                onStdout: (context, chars) =>
                    onCallback?.call(context, chars, false),
                onStderr: (context, chars) =>
                    onCallback?.call(context, chars, true),
              ),
            ],
          ),
        ),
        DockerCompose.init(
          composeFile: File(composeFilePath),
          workingDirectory: appDirectoryPath,
          detach: true,
          onCallback: onCallback,
        ),
      ],
    );
  }
}

class CreateDirectory extends ConfigureStep {
  final String path;
  final bool recursive;
  final bool deleteIfExists;
  const CreateDirectory(
    this.path, {
    this.recursive = false,
    this.deleteIfExists = false,
  });
  @override
  Step configure() => Runnable((context) async {
    final bool exists = await Directory(path).exists();
    if (exists) {
      if (!deleteIfExists) {
        return;
      }
      await Directory(path).delete(recursive: true);
    }
    await Directory(path).create(recursive: recursive);
  });
}
