import 'dart:io';

import 'package:path/path.dart' as path;
import 'package:stepflow/core.dart';
import 'package:td_erpnext/src/steps/create_directory.dart';
import 'package:td_erpnext/src/steps/docker.dart';
import 'package:stepflow/src/io/steps/log_print.dart';

class ERPNextBackup extends ConfigureStep {
  final DockerContainer container;
  final String currentSiteName;
  final DockerOutputCallback? onCallback;
  final String backupSourcePath;
  final String backupDestinationPath;

  ERPNextBackup({
    required this.container,
    required this.currentSiteName,
    required this.onCallback,
    required this.backupSourcePath,
    required this.backupDestinationPath,
  });

  late final DockerOutputCallback _grayedCallback = (context, chars, error) =>
      this.onCallback?.call(
        context,
        LogColor.grayed(String.fromCharCodes(chars)).codeUnits,
        error,
      );

  @override
  Step configure() {
    final String backupDestinationPackagePath = path.join(
      backupDestinationPath,
      DateTime.now()
          .toLocal()
          .toIso8601String()
          .substring(0, 18)
          .replaceAll(":", "_"),
    );
    return Chain(
      steps: [
        Conditional(
          condition: !Directory(backupDestinationPackagePath).existsSync(),
          child: Chain(
            steps: [
              LogASCIIContext("Create backup directory..."),
              CreateDirectory(backupDestinationPackagePath, recursive: true),
            ],
          ),
        ),
        LogASCIIContext(
          "Backup frappe files inside running docker container...",
        ),
        Chain(
          steps: [
            Docker.execute(
              container: container,
              program: "bench",
              arguments: [
                "--site",
                currentSiteName,
                "backup",
                "--with-files",
                "--compress",
              ],
              onCallback: _grayedCallback,
            ),
            // The bench backup command creates files in sites/<site>/private/backups
            // The exact filenames are generated by bench.
            // We expect the backupSourcePath to point to that directory.
            LogASCIIContext(
              "Copy frappe backups from container to $backupDestinationPackagePath...",
            ),
            Docker.copy(
              source: DockerLocation.container(container, backupSourcePath),
              destination: DockerLocation.host(backupDestinationPackagePath),
              onCallback: _grayedCallback,
            ),
            LogASCIIContext(
              "Delete frappe backups inside running docker container...",
            ),
            Docker.execute(
              container: container,
              settings: DockerExecSettings(
                workingDirectory: path.dirname(backupSourcePath),
                user: "root",
              ),
              program: "rm",
              arguments: ["-r", "-f", path.basename(backupSourcePath)],
              onCallback: _grayedCallback,
            ),
            LogASCIIContext("Backup docker volume..."),
            Docker.run(
              image: DockerImage.busybox,
              program: "tar",
              arguments: [
                "-cvzf",
                "backup/erpnext_volumes_backup.tar.gz",
                // We want to backup the data volumes.
                // Usually these are mounted under /home/frappe/frappe-bench
                "home/frappe/frappe-bench",
              ],
              settings: DockerRunSettings(
                remove: true,
                volumesFrom: [container],
                volumes: [
                  DockerVolume(
                    hostPath: backupDestinationPackagePath,
                    containerPath: "/backup",
                  ),
                ],
              ),
              onCallback: _grayedCallback,
            ),
            LogASCIIContext(
              "Backup ${LogColor.cyanid(path.basename(backupDestinationPackagePath))} stored under ${path.dirname(backupDestinationPackagePath)}.",
            ),
          ],
        ),
      ],
    );
  }
}
