name: Dart CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - lib
      - bin
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

  build-and-release:
    needs: analyze
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run build script
        run: dart build.dart

      - name: Package Release
        run: |
          zip -r td-erpnext-linux-amd64.zip ./linux-amd64/td-erpnext -x ".git/*"
        working-directory: out/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: out/td-erpnext-linux-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
